module_name: "vcu"

# NOTE: Frequencies will be converted to an integer number of ms for a delay

buckets:
    high_frequency_vcu:
        frequency_hz: 250
        parameters:
            pedalPosition1_mm:
                ADC: ADC1_IN9
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            pedalPosition2_mm:
                ADC: ADC1_IN8
                sensor: linear_pos_sensor_25
                samples_buffered: 1
            brakePressureFront_psi:
                ADC: ADC1_IN14
                sensor: brake_pressure_sensor
                samples_buffered: 1
            pedalPosition1_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            pedalPosition2_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
    low_frequency_vcu:
        frequency_hz: 10
        parameters:
            vcuCurrentRequested_A:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            vcuMaxCurrentLimit_A:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            

    low_frequency_vcu_but_faster:
        frequency_hz: 100
        parameters:
            vcuTemp_C:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

            displayFaultStatus_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
            # State of the vehicle (Disabled, RTD, etc.)
            vehicleState_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            vcuState_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            vcuMcuStatus_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            brakeLightOn_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            vehicleBuzzerOn_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            currentlyMoving_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1